version: '3.4'
services:
  client_pruebas_react:
    build:
      context: ./docker/local
      target: pruebas-react
    volumes:
      - ./:/home/app/
      - shared_dist_pruebas_react:/home/app/dist/
    env_file:
      - ./.env
    tty: true
    ports:
      - "3005:3000"


volumes:
  shared_dist_pruebas_react:
